object Dlg_TiledPreview: TDlg_TiledPreview
  Left = 192
  Top = 103
  Width = 696
  Height = 480
  Caption = 'UTX-Viewer - TiledPreview'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  WindowState = wsMaximized
  OnClose = FormClose
  OnPaint = FormShow
  PixelsPerInch = 96
  TextHeight = 13
end
